baseURL = "https://wress.github.io/"
languageCode = "ja"
title = "WRESS"
HasCJKLanguage = true
disablekinds = ["taxonomy", "taxonomyTerm", "sitemap", "robotsTXT", "RSS"]
timeout = 30000
publishDir = "public"
[frontmatter]
  lastmod = [":fileModTime"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true