import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import Header from "@/components/Header/Header";
import { WRESSTheme } from "@/libs/theme/WRESSTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WRESS公式サイト",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={WRESSTheme}>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
